apiVersion: v1
kind: Pod
metadata:
  name: minion
  labels:
    purpose: demonstrate-minio
spec:
  containers:
  - name: minio-client
    image: bitnami/minio-client
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10;done"]
  restartPolicy: Never
