kind: PersistentVolume
apiVersion: v1
metadata:
  name: airflow-dags
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/usr/share/host/applications/airflow/dags"