apiVersion: hostpathprovisioner.kubevirt.io/v1beta1
kind: HostPathProvisioner
metadata:
  name: hostpath-provisioner
spec:
  imagePullPolicy: Always
  storagePools:
    - name: "local-gp"
      path: "/var/hpvolumes"
    - name: "local-logs"
      path: "/usr/share/host/guest-logs"
  workload:
    nodeSelector:
      kubernetes.io/os: linux