apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-lvm
parameters:
  storage: "lvm"
  volgroup: "app-data"
provisioner: local.csi.openebs.io
volumeBindingMode: WaitForFirstConsumer
